### ISSUE TITLE
redundancy: Relevance to `index.ros.org`?

### ISSUE THREAD

**Issue by eacousineau** [ros2/ros_core_documentation#13]
At present, the description of this package is:

> Documentation for the Core ROS 2 packages which does not fit into one of the individual packages' documentation. http://docs.ros2.org/

Which seems excellent, but it's still a bit confusing because it seems like some of the information in https://index.ros.org/doc/ros2/ *is* a high-level overview that doesn't fit into individual packages.

Can I ask if there's a plan to consolidate these information sources?
If not, is there perhaps an even more clear delineation that would minimize redundancy (and thus hopefully prevent overly stale information from cropping up, and having to make multiple PRs / cross references, etc.)?

Relates #12, in that its resolution might be ref'ing one link vs. two links vs. something else. Would be nice to be concise!

**Comment by jacobperron** [comment]
It is [mentioned on index.ros.org](https://index.ros.org/doc/ros2/#where-to-find-more-information) that

> docs.ros2.org contains current details about ROS 2 internal design and organization.

My understanding is that https://index.ros.org/doc/ros2 is meant to be more user-centric, e.g. how to get up-and-running with ROS 2 from installation to running examples, whereas docs.ros2.org is for explaining internal details. It's possible that these two sites could be consolidated at some point, but I'm not sure if that is the plan.

I think for #12, linking to ROS Index might make the most sense since it also references docs.ros2.org. Or even directly to the hosted API docs (e.g. [rclcpp](http://docs.ros2.org/latest/api/rclcpp/)).

**Comment by clalancette** [comment]
Given that we have now done this consolidation, I'm going to close this issue out.  Feel free to open a new one at https://github.com/ros2/ros2_documentation if you have further issues.
