### ISSUE TITLE
Broken API doc links to this site from index.ros.org

### ISSUE THREAD

**Issue by emersonknapp** [ros2/ros_core_documentation#16]
When browsing ROS2 packages, if I look at a specific package e.g. https://index.ros.org/p/launch_ros/ - the API link leads here http://docs.ros2.org/eloquent/api/launch_ros/ but the resources don't exist.

(related: the wiki link is grayed out, but not actually disabled, and leads to http://wiki.ros.org/launch_ros?distro=eloquent which also doesn't exist for ROS2 packages)

What's the plan for generating API documentation for ROS2 packages outside the few that are currently here?

**Comment by gavanderhoorn** [comment]
Related? https://github.com/ros2/rclcpp/issues/958.

**Comment by emersonknapp** [comment]
Definitely related. I'd like to not close this issue until there is one of two conditions met:
* Link to a ticket tracking work to auto-generate docs for all rosindex packages (vastly preferable)
* Link to a ticket tracking work to not place broken links on the index listings (not good but at least less confusing)

**Comment by dirk-thomas** [comment]
> Link to a ticket tracking work to auto-generate docs for all rosindex packages (vastly preferable)

The goal of having package specific doc jobs (as in ROS 1) which also generate API docs is listed on the roadmap already: https://index.ros.org/doc/ros2/Roadmap/#infrastructure-and-tools. A separate ticket will likely only be created when actual work towards this is started (and I don't expect that this will happen in the near future since it requires a significant amount of resources).

**Comment by emersonknapp** [comment]
Does ROS2 standard practice not include roadmap/backlog tickets for future work?

**Comment by dirk-thomas** [comment]
> Does ROS2 standard practice not include roadmap/backlog tickets for future work?

A new ticket can certainly be created but if nobody is actively working on it I don't see any added value. That is why those items are collected on the roadmap atm. Imo a ticket only makes sense if it is used to collect additional information and/or convey status/progress.

There are already numerous existing tickets label "backlog" and usually nobody ever looks at them again since unfortunately the amount of newly created tickets is usually bigger than what the community can handle/resolve.

**Comment by emersonknapp** [comment]
>  if nobody is actively working on it

Is there an immediate plan to start working on this? (doc job / auto API doc generation) - What is its current priority on the roadmap?

**Comment by dirk-thomas** [comment]
> Is there an immediate plan to start working on this? (doc job / auto API doc generation) - What is its current priority on the roadmap?

It is currently not scheduled to be worked on since other tasks which target Foxy and therefore have a strict deadline have a higher priority.

**Comment by wjwwood** [comment]
@hidmic can you take a look at this and also move it (I cannot automagically transfer it across org units) to ros-infrastructure/index.ros.org?

**Comment by hidmic** [comment]
> Link to a ticket tracking work to auto-generate docs for all rosindex packages (vastly preferable)

As @dirk-thomas already stated, this is not trivial and it will demand a significant amount of resources.

> Link to a ticket tracking work to not place broken links on the index listings (not good but at least less confusing)

See https://github.com/ros-infrastructure/rosindex/issues/218. I'll try to address it myself sometime this week. But for now, I'll close this.
